runtime: custom

env: flex

env_variables:
  DATABASE_URL: "mysql://avnadmin:AVNS_qzoVPyCwDgkQGOvnhtt@dreamhacker-dreamhacker.a.aivencloud.com:14783/defaultdb"
  jwtSecretKey: "3e+9eSUw+8X5jN86WFNBN2Fxg8IkiP+R/0QYpInCYKw"
  jwtRefreshTokenKey: "o+qG20co6QUpN1ARtLOduev9r8W1GemZqPFjrh2brKU"
